package model;

public class Friend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend_1_id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    private Integer friend1Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column friend.friend_2_id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    private Integer friend2Id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.id
     *
     * @return the value of friend.id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.id
     *
     * @param id the value for friend.id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend_1_id
     *
     * @return the value of friend.friend_1_id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    public Integer getFriend1Id() {
        return friend1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend_1_id
     *
     * @param friend1Id the value for friend.friend_1_id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    public void setFriend1Id(Integer friend1Id) {
        this.friend1Id = friend1Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column friend.friend_2_id
     *
     * @return the value of friend.friend_2_id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    public Integer getFriend2Id() {
        return friend2Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column friend.friend_2_id
     *
     * @param friend2Id the value for friend.friend_2_id
     *
     * @mbg.generated Sat Feb 20 21:07:03 CST 2021
     */
    public void setFriend2Id(Integer friend2Id) {
        this.friend2Id = friend2Id;
    }
}