package model;

public class SysPosition {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_position.id
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_position.area_name
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    private String areaName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_position.area_code
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    private Integer areaCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_position.city_code
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_position.level
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    private Boolean level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_position.area_index
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    private String areaIndex;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_position.id
     *
     * @return the value of sys_position.id
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_position.id
     *
     * @param id the value for sys_position.id
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_position.area_name
     *
     * @return the value of sys_position.area_name
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_position.area_name
     *
     * @param areaName the value for sys_position.area_name
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName == null ? null : areaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_position.area_code
     *
     * @return the value of sys_position.area_code
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public Integer getAreaCode() {
        return areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_position.area_code
     *
     * @param areaCode the value for sys_position.area_code
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public void setAreaCode(Integer areaCode) {
        this.areaCode = areaCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_position.city_code
     *
     * @return the value of sys_position.city_code
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_position.city_code
     *
     * @param cityCode the value for sys_position.city_code
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_position.level
     *
     * @return the value of sys_position.level
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public Boolean getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_position.level
     *
     * @param level the value for sys_position.level
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public void setLevel(Boolean level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_position.area_index
     *
     * @return the value of sys_position.area_index
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public String getAreaIndex() {
        return areaIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_position.area_index
     *
     * @param areaIndex the value for sys_position.area_index
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    public void setAreaIndex(String areaIndex) {
        this.areaIndex = areaIndex == null ? null : areaIndex.trim();
    }
}