package mapper;

import java.util.List;
import model.SysPosition;
import model.SysPositionExample;
import org.apache.ibatis.annotations.Param;

public interface SysPositionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    long countByExample(SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int deleteByExample(SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int insert(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int insertSelective(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    List<SysPosition> selectByExample(SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    SysPosition selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int updateByExampleSelective(@Param("record") SysPosition record, @Param("example") SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int updateByExample(@Param("record") SysPosition record, @Param("example") SysPositionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int updateByPrimaryKeySelective(SysPosition record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_position
     *
     * @mbg.generated Sat Jul 18 10:47:04 CST 2020
     */
    int updateByPrimaryKey(SysPosition record);
}